name: Manually Publish

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Fix Gradle permission
        run: chmod +x ./gradlew
        
      - name: Dry run
        run: ./gradlew -Prun_number=${{ github.run_number }}

      - name: Setup Forge env
        run: ./gradlew setup -Prun_number=${{ github.run_number }}

      - name: Get version
        run: echo "CLEANROOM_VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Stop Gradle daemon
        run: ./gradlew --stop

      - name: Build Jars
        run: ./gradlew installerJar -Prun_number=${{ github.run_number }}

      - name: Stop Gradle daemon again
        run: ./gradlew --stop

      - name: Publish to maven for mod development
        run: ./gradlew publish -PcleanroomUsername=${{ secrets.CLEANROOM_MAVEN_USERNAME }} -PcleanroomPassword="${{ secrets.CLEANROOM_MAVEN_PASSWORD }}" -Prun_number=${{ github.run_number }}

      - name: Trigger download server update
        run: |
          curl -X POST "http://download.cleanroommc.com/api/webhook" \
            -H "Content-Type: application/json" \
            -d "{\"secret\":\"${{ secrets.DOWNLOAD_UPDATE_TOKEN }}\",\"count\":10}"